version: '3'
services:
  data:
    image: "postgres:9"
    ports:
      - "5432:5432"
    volumes:
      - ".data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "sprio"
      POSTGRES_DB: "warehouse"